project_id = "vqbmbbuhdnxbuuatxmla"

[functions.ai-tutor]
verify_jwt = false

[functions.generate-custom-questions]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.increment-generation]
verify_jwt = true

[functions.activate-promo-code]
verify_jwt = true

[functions.extract-youtube-transcript]
verify_jwt = false

[functions.youtube-transcript-alternative]
verify_jwt = false

[functions.correct-enhance-text]
verify_jwt = true

[functions.find-relevant-sources]
verify_jwt = false

[functions.generate-study-materials]
verify_jwt = true

[functions.youtube-search]
verify_jwt = false

[functions.ocr-image-text]
verify_jwt = true

[functions.extract-notes]
verify_jwt = true

[functions.ai-schedule-planner]
verify_jwt = true

[functions.create-study-group]
verify_jwt = true

[functions.get-video-details]
verify_jwt = false